name: Deploy to NAS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  redeploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH redeploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          script: |
            export PATH=$PATH:/opt/bin:/opt/sbin:/usr/local/bin
            cd /volume1/docker/nasa/mega
            ./redeploy.sh iot-ws
